# Generated by Django 3.2.20 on 2023-07-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useridentifier',
            options={'verbose_name': 'Идентификатор', 'verbose_name_plural': 'Идентификаторы'},
        ),
    ]
